name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run tests
        run: python -m unittest discover -s tests
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Heroku CLI
        uses: akhileshns/heroku-action@v4
        with:
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}
          app-name: <your-heroku-app-name>
          
      - name: Deploy to Heroku
        run: |
          # Add your Heroku deployment commands here
          # For example:
          git remote add heroku https://git.heroku.com/<your-heroku-app-name>.git
          git push heroku main
