name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Heroku
      run: |
        # Use secrets for sensitive information
        echo "Deploying application to Heroku..."
        heroku login -i <<EOF
        ${{ secrets.HEROKU_API_KEY }}
        EOF
        git push heroku main
